// Unit tests for the pure index builders in src/ai/note-index.js.
// No DOM / no I/O — these run in plain Node.
import { describe, it, expect } from 'vitest';
import {
  buildIndexJson,
  buildIndexMarkdown,
  INDEX_JSON_NAME,
  INDEX_MD_NAME,
  INDEX_SCHEMA_VERSION,
} from '../src/ai/note-index.js';

const noteA = {
  id: '2026-01-02 - Alpha.md',
  wrenId: 'wren-aaaaaaaaaaaa',
  filename: '2026-01-02 - Alpha.md',
  title: 'Alpha',
  summary: 'First note',
  due: '2026-02-01',
  tags: ['status:todo', 'project:wren'],
  color: 'amber',
  created: '2026-01-02T00:00:00.000Z',
  modified: '2026-01-02T08:00:00.000Z',
};
const noteB = {
  id: 'drive-file-id-xyz',
  wrenId: 'wren-bbbbbbbbbbbb',
  name: '2026-01-05 - Beta.md', // adapter-style `name` (Drive)
  title: 'Beta',
  summary: '',
  due: '',
  tags: [],
  color: 'default',
  created: '2026-01-05T00:00:00.000Z',
  modified: '2026-01-05T08:00:00.000Z',
};

describe('constants', () => {
  it('exposes the managed file names', () => {
    expect(INDEX_JSON_NAME).toBe('.wren-index.json');
    expect(INDEX_MD_NAME).toBe('_index.md');
  });
});

describe('buildIndexJson', () => {
  it('produces the documented schema shape', () => {
    const idx = buildIndexJson([noteA], 'fs');
    expect(idx.schemaVersion).toBe(INDEX_SCHEMA_VERSION);
    expect(idx.backend).toBe('fs');
    expect(idx.count).toBe(1);
    expect(typeof idx.generatedAt).toBe('string');
    expect(() => new Date(idx.generatedAt).toISOString()).not.toThrow();
    expect(idx.notes[0]).toEqual({
      wrenId: 'wren-aaaaaaaaaaaa',
      storageId: '2026-01-02 - Alpha.md',
      file: '2026-01-02 - Alpha.md',
      title: 'Alpha',
      summary: 'First note',
      due: '2026-02-01',
      tags: ['status:todo', 'project:wren'],
      color: 'amber',
      created: '2026-01-02T00:00:00.000Z',
      modified: '2026-01-02T08:00:00.000Z',
    });
  });

  it('sorts notes by modified descending', () => {
    const idx = buildIndexJson([noteA, noteB], 'fs');
    expect(idx.notes.map((n) => n.wrenId)).toEqual([
      'wren-bbbbbbbbbbbb', // 01-05 newest
      'wren-aaaaaaaaaaaa', // 01-02
    ]);
  });

  it('keeps all keys present with empty defaults (stable schema)', () => {
    const idx = buildIndexJson([noteB], 'drive');
    const entry = idx.notes[0];
    expect(entry.summary).toBe('');
    expect(entry.due).toBe('');
    expect(entry.tags).toEqual([]);
    expect(entry.color).toBe('default');
    // Drive entry: storageId = opaque id, file = the human `name`.
    expect(entry.storageId).toBe('drive-file-id-xyz');
    expect(entry.file).toBe('2026-01-05 - Beta.md');
  });

  it('handles an empty folder (count 0, empty notes array)', () => {
    const idx = buildIndexJson([], 'fs');
    expect(idx.count).toBe(0);
    expect(idx.notes).toEqual([]);
  });

  it('does not mutate the input array', () => {
    const input = [noteA, noteB];
    const snapshot = [...input];
    buildIndexJson(input, 'fs');
    expect(input).toEqual(snapshot);
    expect(input[0]).toBe(noteA);
  });
});

describe('buildIndexMarkdown', () => {
  it('emits a banner, metadata block, and a table row per note', () => {
    const md = buildIndexMarkdown([noteA, noteB], 'fs');
    expect(md).toContain('AUTO-GENERATED by Wren');
    expect(md).toContain('do not edit by hand');
    expect(md).toContain('- Notes: 2');
    expect(md).toContain('- Backend: fs');
    expect(md).toContain('| Modified | Title | Tags | Due | Summary | File | wrenId |');
    // Newest first.
    const betaIdx = md.indexOf('Beta');
    const alphaIdx = md.indexOf('Alpha');
    expect(betaIdx).toBeGreaterThan(-1);
    expect(betaIdx).toBeLessThan(alphaIdx);
    // 2 data rows + 1 header + 1 divider = 4 table lines.
    expect(md.split('\n').filter((l) => l.startsWith('|')).length).toBe(4);
  });

  it('escapes pipes and collapses newlines so the table never breaks', () => {
    const tricky = {
      ...noteA,
      title: 'A | B',
      summary: 'line one\nline two: with colon | and pipe',
    };
    const md = buildIndexMarkdown([tricky], 'fs');
    const row = md.split('\n').find((l) => l.includes('wren-aaaa'));
    expect(row).toContain('A \\| B');
    expect(row).toContain('line one line two: with colon \\| and pipe');
    // Escaped pipes don't add real columns: 7 cols => 8 unescaped pipes.
    const unescaped = (row.match(/(?<!\\)\|/g) || []).length;
    expect(unescaped).toBe(8);
  });

  it('renders an empty folder as a valid header + "No notes yet."', () => {
    const md = buildIndexMarkdown([], 'drive');
    expect(md).toContain('# Wren Note Index');
    expect(md).toContain('- Notes: 0');
    expect(md).toContain('No notes yet.');
    expect(md).not.toContain('| Modified |');
  });
});
