// note-index.js
//
// Pure builders for Wren's auto-generated note catalog (AI-readable layer,
// Phase 2). No I/O here — these functions take the already-loaded, fully-parsed
// in-memory notes collection and return serializable artifacts. app-controller
// owns the debounce + the adapter.writeManagedFile() calls.
//
// Two artifacts are produced, both written into the notes-folder root and both
// treated as Wren-managed (regenerated automatically, excluded from the notes
// list via isReservedNoteName in notes-store.js):
//
//   .wren-index.json  machine-readable source of truth for AI tools / the
//                     future Wren MCP server. Stable schema (schemaVersion).
//   _index.md         human + AI readable markdown mirror (scannable table),
//                     for when an agent only has the folder, not the JSON.
//
// The in-memory note shape this consumes (built by app-controller) is:
//   { id, wrenId, filename|name, title, summary, due, tags, color,
//     created, modified, ... }
// where `id` is the STORAGE identity (FS filename / Drive opaque fileId) and
// `wrenId` is the logical id (frontmatter `id`, "wren-...").

export const INDEX_JSON_NAME = '.wren-index.json';
export const INDEX_MD_NAME = '_index.md';

// Current .wren-index.json schema version. Bump when the `notes[]` entry shape
// changes in a non-additive way so consumers can branch on it.
export const INDEX_SCHEMA_VERSION = 1;

/**
 * Return a new array sorted by `modified` descending (newest first). Stable for
 * equal timestamps; never mutates the input. Missing timestamps sort last.
 */
function sortByModifiedDesc(notes) {
  return [...(notes || [])].sort((a, b) => {
    const am = a?.modified || '';
    const bm = b?.modified || '';
    return am < bm ? 1 : am > bm ? -1 : 0;
  });
}

// The human/back-end filename for a note. In-memory notes use `filename`;
// adapter listings use `name`. Fall back to the storage id (FS: that IS the
// filename; Drive: the opaque id, the best we have).
function fileNameOf(n) {
  return n?.name || n?.filename || n?.id || '';
}

function cleanTags(tags) {
  return Array.isArray(tags)
    ? tags.filter((t) => typeof t === 'string' && t.trim().length > 0)
    : [];
}

/**
 * Build the machine-readable index object.
 *
 * All keys are always present (stable schema) — empty optionals are '' or [],
 * never omitted — so consumers can rely on the shape without existence checks.
 *
 * @param {Array<Object>} notes      fully-parsed in-memory notes
 * @param {string} backendId         adapter.backendId() ('fs' | 'drive')
 * @returns {{schemaVersion:number, generatedAt:string, backend:string,
 *            count:number, notes:Array<Object>}}
 */
export function buildIndexJson(notes, backendId) {
  const sorted = sortByModifiedDesc(notes);
  return {
    schemaVersion: INDEX_SCHEMA_VERSION,
    generatedAt: new Date().toISOString(),
    backend: backendId || '',
    count: sorted.length,
    notes: sorted.map((n) => ({
      wrenId: n.wrenId || '',
      storageId: n.id || '',
      file: fileNameOf(n),
      title: n.title || '',
      summary: n.summary || '',
      due: n.due || '',
      tags: cleanTags(n.tags),
      color: n.color || 'default',
      created: n.created || '',
      modified: n.modified || '',
    })),
  };
}

/**
 * Escape a value for safe inclusion in a single markdown table cell:
 * collapse newlines to spaces and escape pipes so they don't split the column.
 * Backslashes are escaped first so an existing "\|" in the source can't combine
 * with our pipe-escape into a malformed sequence.
 */
function escapeCell(value) {
  return String(value == null ? '' : value)
    .replace(/\\/g, '\\\\')
    .replace(/\r?\n/g, ' ')
    .replace(/\|/g, '\\|')
    .trim();
}

/**
 * Build the human + AI readable markdown mirror: an auto-generated banner, a
 * small metadata block, then a table (one row per note, newest first). An empty
 * folder yields a valid header plus "No notes yet." and count 0 — intentional,
 * not a placeholder.
 *
 * @param {Array<Object>} notes
 * @param {string} backendId
 * @returns {string} markdown
 */
export function buildIndexMarkdown(notes, backendId) {
  const sorted = sortByModifiedDesc(notes);
  const lines = [
    '<!-- AUTO-GENERATED by Wren — do not edit by hand. -->',
    '<!-- Regenerated on every note change; manual edits will be overwritten. -->',
    '',
    '# Wren Note Index',
    '',
    `- Generated: ${new Date().toISOString()}`,
    `- Notes: ${sorted.length}`,
    `- Backend: ${backendId || ''}`,
    '',
  ];

  if (sorted.length === 0) {
    lines.push('No notes yet.', '');
    return lines.join('\n');
  }

  lines.push(
    '| Modified | Title | Tags | Due | Summary | File | wrenId |',
    '| --- | --- | --- | --- | --- | --- | --- |'
  );
  for (const n of sorted) {
    const cells = [
      escapeCell(n.modified),
      escapeCell(n.title),
      escapeCell(cleanTags(n.tags).join(', ')),
      escapeCell(n.due),
      escapeCell(n.summary),
      escapeCell(fileNameOf(n)),
      escapeCell(n.wrenId),
    ];
    lines.push(`| ${cells.join(' | ')} |`);
  }
  lines.push('');
  return lines.join('\n');
}
